[project]
name = "plat"
version = "0.0.1"
description = "Python Lagrangian Atmospheric Trajectory model"
requires-python = ">=3.8"
dependencies = [
    "xarray[complete]",
    "dask",
    "numpy",
]

[project.optional-dependencies]
test = [
    "pytest",
]
dev = [
    "ruff",
]
